require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe AlarmNotificationsController do

  # This should return the minimal set of attributes required to create a valid
  # AlarmNotification. As you add validations to AlarmNotification, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "tank_name" => "MyString" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # AlarmNotificationsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all alarm_notifications as @alarm_notifications" do
      alarm_notification = AlarmNotification.create! valid_attributes
      get :index, {}, valid_session
      assigns(:alarm_notifications).should eq([alarm_notification])
    end
  end

  describe "GET show" do
    it "assigns the requested alarm_notification as @alarm_notification" do
      alarm_notification = AlarmNotification.create! valid_attributes
      get :show, {:id => alarm_notification.to_param}, valid_session
      assigns(:alarm_notification).should eq(alarm_notification)
    end
  end

  describe "GET new" do
    it "assigns a new alarm_notification as @alarm_notification" do
      get :new, {}, valid_session
      assigns(:alarm_notification).should be_a_new(AlarmNotification)
    end
  end

  describe "GET edit" do
    it "assigns the requested alarm_notification as @alarm_notification" do
      alarm_notification = AlarmNotification.create! valid_attributes
      get :edit, {:id => alarm_notification.to_param}, valid_session
      assigns(:alarm_notification).should eq(alarm_notification)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new AlarmNotification" do
        expect {
          post :create, {:alarm_notification => valid_attributes}, valid_session
        }.to change(AlarmNotification, :count).by(1)
      end

      it "assigns a newly created alarm_notification as @alarm_notification" do
        post :create, {:alarm_notification => valid_attributes}, valid_session
        assigns(:alarm_notification).should be_a(AlarmNotification)
        assigns(:alarm_notification).should be_persisted
      end

      it "redirects to the created alarm_notification" do
        post :create, {:alarm_notification => valid_attributes}, valid_session
        response.should redirect_to(AlarmNotification.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved alarm_notification as @alarm_notification" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmNotification.any_instance.stub(:save).and_return(false)
        post :create, {:alarm_notification => { "tank_name" => "invalid value" }}, valid_session
        assigns(:alarm_notification).should be_a_new(AlarmNotification)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmNotification.any_instance.stub(:save).and_return(false)
        post :create, {:alarm_notification => { "tank_name" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested alarm_notification" do
        alarm_notification = AlarmNotification.create! valid_attributes
        # Assuming there are no other alarm_notifications in the database, this
        # specifies that the AlarmNotification created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        AlarmNotification.any_instance.should_receive(:update_attributes).with({ "tank_name" => "MyString" })
        put :update, {:id => alarm_notification.to_param, :alarm_notification => { "tank_name" => "MyString" }}, valid_session
      end

      it "assigns the requested alarm_notification as @alarm_notification" do
        alarm_notification = AlarmNotification.create! valid_attributes
        put :update, {:id => alarm_notification.to_param, :alarm_notification => valid_attributes}, valid_session
        assigns(:alarm_notification).should eq(alarm_notification)
      end

      it "redirects to the alarm_notification" do
        alarm_notification = AlarmNotification.create! valid_attributes
        put :update, {:id => alarm_notification.to_param, :alarm_notification => valid_attributes}, valid_session
        response.should redirect_to(alarm_notification)
      end
    end

    describe "with invalid params" do
      it "assigns the alarm_notification as @alarm_notification" do
        alarm_notification = AlarmNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmNotification.any_instance.stub(:save).and_return(false)
        put :update, {:id => alarm_notification.to_param, :alarm_notification => { "tank_name" => "invalid value" }}, valid_session
        assigns(:alarm_notification).should eq(alarm_notification)
      end

      it "re-renders the 'edit' template" do
        alarm_notification = AlarmNotification.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        AlarmNotification.any_instance.stub(:save).and_return(false)
        put :update, {:id => alarm_notification.to_param, :alarm_notification => { "tank_name" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested alarm_notification" do
      alarm_notification = AlarmNotification.create! valid_attributes
      expect {
        delete :destroy, {:id => alarm_notification.to_param}, valid_session
      }.to change(AlarmNotification, :count).by(-1)
    end

    it "redirects to the alarm_notifications list" do
      alarm_notification = AlarmNotification.create! valid_attributes
      delete :destroy, {:id => alarm_notification.to_param}, valid_session
      response.should redirect_to(alarm_notifications_url)
    end
  end

end
