require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe LivestocksController do

  # This should return the minimal set of attributes required to create a valid
  # Livestock. As you add validations to Livestock, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { { "description" => "MyText" } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # LivestocksController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all livestocks as @livestocks" do
      livestock = Livestock.create! valid_attributes
      get :index, {}, valid_session
      assigns(:livestocks).should eq([livestock])
    end
  end

  describe "GET show" do
    it "assigns the requested livestock as @livestock" do
      livestock = Livestock.create! valid_attributes
      get :show, {:id => livestock.to_param}, valid_session
      assigns(:livestock).should eq(livestock)
    end
  end

  describe "GET new" do
    it "assigns a new livestock as @livestock" do
      get :new, {}, valid_session
      assigns(:livestock).should be_a_new(Livestock)
    end
  end

  describe "GET edit" do
    it "assigns the requested livestock as @livestock" do
      livestock = Livestock.create! valid_attributes
      get :edit, {:id => livestock.to_param}, valid_session
      assigns(:livestock).should eq(livestock)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Livestock" do
        expect {
          post :create, {:livestock => valid_attributes}, valid_session
        }.to change(Livestock, :count).by(1)
      end

      it "assigns a newly created livestock as @livestock" do
        post :create, {:livestock => valid_attributes}, valid_session
        assigns(:livestock).should be_a(Livestock)
        assigns(:livestock).should be_persisted
      end

      it "redirects to the created livestock" do
        post :create, {:livestock => valid_attributes}, valid_session
        response.should redirect_to(Livestock.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved livestock as @livestock" do
        # Trigger the behavior that occurs when invalid params are submitted
        Livestock.any_instance.stub(:save).and_return(false)
        post :create, {:livestock => { "description" => "invalid value" }}, valid_session
        assigns(:livestock).should be_a_new(Livestock)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Livestock.any_instance.stub(:save).and_return(false)
        post :create, {:livestock => { "description" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested livestock" do
        livestock = Livestock.create! valid_attributes
        # Assuming there are no other livestocks in the database, this
        # specifies that the Livestock created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Livestock.any_instance.should_receive(:update_attributes).with({ "description" => "MyText" })
        put :update, {:id => livestock.to_param, :livestock => { "description" => "MyText" }}, valid_session
      end

      it "assigns the requested livestock as @livestock" do
        livestock = Livestock.create! valid_attributes
        put :update, {:id => livestock.to_param, :livestock => valid_attributes}, valid_session
        assigns(:livestock).should eq(livestock)
      end

      it "redirects to the livestock" do
        livestock = Livestock.create! valid_attributes
        put :update, {:id => livestock.to_param, :livestock => valid_attributes}, valid_session
        response.should redirect_to(livestock)
      end
    end

    describe "with invalid params" do
      it "assigns the livestock as @livestock" do
        livestock = Livestock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Livestock.any_instance.stub(:save).and_return(false)
        put :update, {:id => livestock.to_param, :livestock => { "description" => "invalid value" }}, valid_session
        assigns(:livestock).should eq(livestock)
      end

      it "re-renders the 'edit' template" do
        livestock = Livestock.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Livestock.any_instance.stub(:save).and_return(false)
        put :update, {:id => livestock.to_param, :livestock => { "description" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested livestock" do
      livestock = Livestock.create! valid_attributes
      expect {
        delete :destroy, {:id => livestock.to_param}, valid_session
      }.to change(Livestock, :count).by(-1)
    end

    it "redirects to the livestocks list" do
      livestock = Livestock.create! valid_attributes
      delete :destroy, {:id => livestock.to_param}, valid_session
      response.should redirect_to(livestocks_url)
    end
  end

end
